import { SaleProcess } from "@/app/lib/types/sales";
import { RealEstate, Client, Offer, PropertyItem, PropertyLegalDetails, Agent } from "@/app/lib/types/database";

// Dados mockados completos para o contrato
export const MOCK_SALE_DATA: SaleProcess = {
  id: "mock-sale-1",
  offer_id: "mock-offer-1",
  status: "active",
  current_step_index: 0,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  offer: {
    id: "mock-offer-1",
    property_id: "mock-property-1",
    client_id: "mock-buyer-1",
    agent_id: null,
    offer_amount: 1430000,
    payment_type: "mixed",
    down_payment: 30000,
    financing_amount: 1400000,
    financing_term_months: 360,
    status: "accepted",
    created_at: new Date().toISOString(),
  } as Offer,

  property: {
    id: "mock-property-1",
    code: "REAP-001",
    type: "apartment",
    status: "pending",
    sale_price: 1430000,
    address_street: "Rua Guimarães Rosa",
    address_number: "203",
    address_complement: "Aptº 408",
    address_neighborhood: "Barra da Tijuca",
    address_city: "Rio de Janeiro",
    address_state: "RJ",
    address_zip: "22.793-620",
    bedrooms: 3,
    bathrooms: 2,
    parking_spaces: 2,
    usable_area: 120,
    total_area: 120,
    suites: 1,
    floor_number: 4,
    condominium_fee: 2500,
    property_tax: 500,
    property_tax_period: "monthly",
    iptu_number: "1.422.545-2",
    features: ["piscina", "academia", "salão de festas"],
    description: "Apartamento amplo e bem localizado",
    transaction_type: "sale",
    is_condo_fee_exempt: false,
    is_property_tax_exempt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),

    property_legal_details: {
      property_id: "mock-property-1",
      has_deed: true,
      is_registered: true,
      accepts_financing: true,
      has_exclusivity: true,
      authorization_status: "written_exclusive",
      matricula: "48.365",
      incorporation_registry: "1.422.545-2",
      acquisition_origin: "R-12 da matrícula 48.365 do 9º Ofício de Registro de Imóveis",
      created_at: new Date().toISOString(),
    } as PropertyLegalDetails,

    real_estate_owners: [
      {
        client: {
          id: "mock-seller-1",
          name: "NASY DA SILVA MACHADO",
          email: "grasielasmachado@gmail.com",
          phone: "(21) 99311-1202",
          whatsapp: null,
          notes: "Aposentada, viúva",
          instagram: null,
          nationality: "Brasileira",
          profession: "Aposentada",
          marital_status: "Viúva",
          union_stable: false,
          rg: "705.713.417-72",
          rg_issuer: "Detran/RJ",
          rg_issue_date: "14/04/2025",
          cpf: "705.713.417-72",
          father_name: "Olavo José da Silva",
          mother_name: "Giuseppina Elide Scapin da Silva",
          address_street: "Rua Guimarães Rosa",
          address_number: "203",
          address_complement: "Aptº 408",
          address_neighborhood: "Barra da Tijuca",
          address_city: "Rio de Janeiro",
          address_state: "RJ",
          address_zip: "22.793-620",
          bank_accounts: [
            {
              bank_name: "Banco Itaú (341)",
              agency: "1234",
              account_number: "12345-6",
              account_type: "Conta Corrente",
              holder_name: "Nasy da Silva Machado",
              pix_key: "705.713.417-72",
              pix_key_type: "CPF"
            }
          ],
          user_id: null,
          created_at: new Date().toISOString(),
        } as Client,
      },
      {
        client: {
          id: "mock-seller-2",
          name: "GRASIELA DA SILVA MACHADO",
          email: "grasielasmachado@gmail.com",
          phone: "(21) 99311-1202",
          whatsapp: null,
          notes: "Economista, divorciada",
          instagram: null,
          nationality: "Brasileira",
          profession: "Economista",
          marital_status: "Divorciada",
          union_stable: false,
          rg: "00048847454",
          rg_issuer: "Detran/RJ",
          rg_issue_date: "10/03/2025",
          cpf: "018.617.777-10",
          father_name: "Amandio da Silva Machado",
          mother_name: "Nasy da Silva Machado",
          address_street: "Rua Guimarães Rosa",
          address_number: "203",
          address_complement: "Aptº 408",
          address_neighborhood: "Barra da Tijuca",
          address_city: "Rio de Janeiro",
          address_state: "RJ",
          address_zip: "22.793-620",
          user_id: null,
          bank_accounts: [
            {
              bank_name: "Banco Bradesco (237)",
              agency: "4321",
              account_number: "98765-4",
              account_type: "Conta Corrente",
              holder_name: "Grasiela da Silva Machado",
              pix_key: "018.617.777-10",
              pix_key_type: "CPF"
            }
          ],
          created_at: new Date().toISOString(),
        } as Client,
      },
      {
        client: {
          id: "mock-seller-3",
          name: "GISELA DA SILVA MACHADO",
          email: "gisela.s.machado@gmail.com",
          phone: null,
          whatsapp: null,
          notes: "Contadora, casada",
          instagram: null,
          nationality: "Brasileira",
          profession: "Contadora",
          marital_status: "Casado",
          union_stable: false,
          rg: "00263615910",
          rg_issuer: "Detran/RJ",
          rg_issue_date: "14/03/2024",
          cpf: "018.363.217-67",
          father_name: "Amandio da Silva Machado",
          mother_name: "Nasy da Silva Machado",
          address_street: "Avenida Niemeyer",
          address_number: "777",
          address_complement: "aptº 1106",
          address_neighborhood: "São Conrado",
          address_city: "Rio de Janeiro",
          address_state: "RJ",
          address_zip: "22.450-221",

          // Spouse Info
          spouse_name: "Ricardo Morena de Almeida",
          spouse_nationality: "Brasileiro",
          spouse_profession: "Analista de Sistemas",
          spouse_rg: "08865094",
          spouse_rg_issuer: "Detran/RJ",
          spouse_cpf: "016.366.297-50",
          spouse_father_name: "Nome do Sogro Exemplo", // Added mock parent names as they weren't in the snippet I saw but are required
          spouse_mother_name: "Nome da Sogra Exemplo",

          bank_accounts: [
            {
              bank_name: "Banco Santander (033)",
              agency: "5678",
              account_number: "54321-0",
              account_type: "Conta Corrente",
              holder_name: "Gisela da Silva Machado",
              pix_key: "gisela.s.machado@gmail.com",
              pix_key_type: "Email"
            }
          ],

          user_id: null,
          created_at: new Date().toISOString(),
        } as Client,
      },
    ],
    real_estate_agents: [
      {
        agent_role: "Intermediadora",
        agent: {
          id: "agent-1",
          user_id: "user-agent-1",
          name: "Renata Fonseca Peres (AGAPE IMÓVEIS)",
          full_name: "Renata Fonseca Peres",
          email: "contato@renataimoveis.com",
          phone: "(21) 99311-1202",
          creci: "7583 (Jurídico)",
          cnpj: "19.957.555/0001-49",
          company_name: "Ágape Imóveis Ltda-Me",
          address_full: "Av. das Américas, 3939, Bloco 1, Sala 215, Barra da Tijuca, Rio de Janeiro - RJ",
          roles: ["broker"],
          show_in_ad: true,
          is_company: true,
          created_at: new Date().toISOString(),
        } as unknown as Agent,
      },
      {
        agent_role: "Parceiro",
        agent: {
          id: "agent-2",
          user_id: "user-agent-2",
          name: "João Paulo Pereira de Araujo (OHF Engenharia)",
          full_name: "João Paulo Pereira de Araujo",
          email: "secretaria@ohf.com.br",
          phone: "(21) 97022-7935",
          creci: "11848 (Jurídico)",
          cnpj: "42.062.247/0001-52",
          company_name: "OHF Engenharia LTDA",
          address_full: "Estrada dos Três Rios, 1200, Sala 519, Freguesia, Rio de Janeiro - RJ",
          roles: ["broker"],
          show_in_ad: true,
          is_company: true,
          created_at: new Date().toISOString(),
        } as unknown as Agent,
      },
    ],
  } as RealEstate,

  buyer: {
    id: "mock-buyer-1",
    name: "PAULO ROBERTO SAMPAIO JANGUTTA",
    email: "jangutta@tjrj.jus.br",
    phone: "(21) 99999-9999",
    whatsapp: null,
    notes: "Juiz de Direito, divorciado",
    instagram: null,
    nationality: "Brasileiro",
    profession: "Juiz de Direito",
    marital_status: "Divorciado",
    union_stable: false,
    rg: "21702",
    rg_issuer: "Poder Judiciário do Estado do RJ",
    rg_issue_date: "26/10/2010",
    cpf: "943.570.647-91",
    father_name: "Paulo Estevão Jangutta",
    mother_name: "Santana Sampaio",
    address_street: "Rua Ataulpho Coutinho",
    address_number: "101",
    address_complement: "bloco 2 aptº 803",
    address_neighborhood: "Barra da Tijuca",
    address_city: "Rio de Janeiro",
    address_state: "RJ",
    address_zip: "22.793-520",
    user_id: null,
    created_at: new Date().toISOString(),
  } as Client,

  seller: {
    id: "mock-seller-all", // Representing the primary contact or group for simple views
    name: "NASY DA SILVA MACHADO e filhas",
    email: "grasielasmachado@gmail.com",
    created_at: new Date().toISOString(),
  } as Client, // Keeps top level simple, but real_estate_owners has details

  steps: [],
};

// Bens móveis que ficarão no imóvel
export const MOCK_PROPERTY_ITEMS: PropertyItem[] = [
  {
    id: 1,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Armários embutidos da suíte",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Persiana da suíte",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    property_id: "mock-property-1",
    item_type: "appliance",
    condition: "good",
    stay_option: "stays",
    description: "Ar-condicionado da suíte",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Armários embutidos dos banheiros",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Armário embutido do 1º quarto",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Persiana do 1º quarto",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Persiana da sala",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Armários embutidos da cozinha",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    property_id: "mock-property-1",
    item_type: "appliance",
    condition: "good",
    stay_option: "stays",
    description: "Fogão da cozinha",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 10,
    property_id: "mock-property-1",
    item_type: "appliance",
    condition: "good",
    stay_option: "stays",
    description: "Aquecedor da área de serviço",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 11,
    property_id: "mock-property-1",
    item_type: "built_in",
    condition: "good",
    stay_option: "stays",
    description: "Armários da dependência",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];





