export interface PropertyFeature {
  label: string;
  value: string;
}

export const COMMON_AREAS_LEISURE: PropertyFeature[] = [
  { label: "Academia", value: "gym" },
  { label: "Aquário", value: "aquarium" },
  { label: "Área de lazer", value: "leisure_area" },
  { label: "Arvorismo", value: "tree_climbing" },
  { label: "Bar na piscina", value: "pool_bar" },
  { label: "Brinquedoteca", value: "playroom" },
  { label: "Campo de futebol", value: "football_field" },
  { label: "Campo de golfe", value: "golf_course" },
  { label: "Churrasqueira", value: "barbecue_grill" },
  { label: "Cinema", value: "cinema" },
  { label: "Espaço gourmet", value: "gourmet_space" },
  { label: "Espaço teen", value: "teen_space" },
  { label: "Espaço zen", value: "zen_space" },
  { label: "Forno de pizza", value: "pizza_oven" },
  { label: "Hidromassagem", value: "whirlpool" },
  { label: "Muro de escalada", value: "climbing_wall" },
  { label: "Ofurô", value: "hot_tub" },
  { label: "Piscina", value: "pool" },
  { label: "Piscina aquecida", value: "heated_pool" },
  { label: "Piscina coberta", value: "indoor_pool" },
  { label: "Piscina infantil", value: "kids_pool" },
  { label: "Piscina para adulto", value: "adult_pool" },
  { label: "Pista de cooper", value: "jogging_track" },
  { label: "Pista de skate", value: "skate_park" },
  { label: "Playground", value: "playground" },
  { label: "Quadra de esporte", value: "sports_court" },
  { label: "Quadra de tênis", value: "tennis_court" },
  { label: "Quadra poliesportiva", value: "multisports_court" },
  { label: "Redário", value: "hammock_area" },
  { label: "Sala de massagem", value: "massage_room" },
  { label: "Salão de festas", value: "party_room" },
  { label: "Salão de jogos", value: "game_room" },
  { label: "Sauna", value: "sauna" },
  { label: "Spa", value: "spa" },
];

export const COMMON_AREAS_CONVENIENCE: PropertyFeature[] = [
  { label: "Acesso de serviço", value: "service_access" },
  { label: "Acesso para deficientes", value: "disabled_access" },
  { label: "Auditório", value: "auditorium" },
  { label: "Biblioteca", value: "library" },
  { label: "Bicicletário", value: "bicycle_storage" },
  { label: "Carregador para carro elétrico", value: "electric_car_charger" },
  { label: "Centro de estética", value: "beauty_center" },
  { label: "Coffee shop", value: "coffee_shop" },
  { label: "Coworking", value: "coworking" },
  { label: "Elevador", value: "elevator" },
  { label: "Elevador de serviço", value: "service_elevator" },
  { label: "Entrada de serviço", value: "service_entrance" },
  { label: "Entrada lateral", value: "side_entrance" },
  { label: "Estacionamento visitantes", value: "visitor_parking" },
  { label: "Gerador elétrico", value: "power_generator" },
  { label: "Heliponto", value: "helipad" },
  { label: "Lavanderia", value: "laundry" },
  { label: "Marina", value: "marina" },
  { label: "Recepção", value: "reception" },
  { label: "Restaurante", value: "restaurant" },
  { label: "Sala de reunião", value: "meeting_room" },
  { label: "Salão de convenção", value: "convention_hall" },
  { label: "Salão multiuso", value: "multipurpose_room" },
  { label: "Serviços pay per use", value: "pay_per_use_services" },
  { label: "Vestiário", value: "locker_room" },
  { label: "Vestiário para diaristas", value: "maids_locker_room" },
];

export const COMMON_AREAS_SECURITY: PropertyFeature[] = [
  { label: "Câmeras de segurança", value: "security_cameras" },
  { label: "Cerca", value: "fence" },
  { label: "Circuito de segurança", value: "security_circuit" },
  { label: "Guarita", value: "guardhouse" },
  { label: "Interfone", value: "intercom" },
  { label: "Portão eletrônico", value: "electronic_gate" },
  { label: "Portaria", value: "concierge" },
  { label: "Portaria 24h", value: "concierge_24h" },
  { label: "Portaria virtual", value: "virtual_concierge" },
  { label: "Ronda/Vigilância", value: "patrol" },
  { label: "Sistema de alarme", value: "alarm_system" },
  { label: "Vigia", value: "watchman" },
  { label: "Vigilância 24h", value: "surveillance_24h" },
];

export const COMMON_AREAS_INFRASTRUCTURE: PropertyFeature[] = [
  { label: "Área para pets", value: "pet_place" },
  { label: "Área verde", value: "green_area" },
  { label: "Árvore frutífera", value: "fruit_tree" },
  { label: "Canil", value: "kennel" },
  { label: "Celeiro", value: "barn" },
  { label: "Cobertura coletiva", value: "collective_roof" },
  { label: "Curral", value: "corral" },
  { label: "Deck", value: "deck" },
  { label: "Gramado", value: "lawn" },
  { label: "Hall de entrada", value: "entrance_hall" },
  { label: "Horta", value: "vegetable_garden" },
  { label: "Jardim", value: "garden" },
  { label: "Lago", value: "lake" },
  { label: "Orquidário", value: "orchid_garden" },
  { label: "Pasto", value: "pasture" },
  { label: "Poço", value: "well" },
  { label: "Poço artesiano", value: "artesian_well" },
  { label: "Pomar", value: "orchard" },
  { label: "Praça", value: "square" },
  { label: "Prédio pastilhado", value: "tiled_building" },
  { label: "Reservatório de água", value: "water_tank" },
  { label: "Rio", value: "river" },
  { label: "Solarium", value: "solarium" },
];

export const COMMON_AREAS: PropertyFeature[] = [
  ...COMMON_AREAS_LEISURE,
  ...COMMON_AREAS_CONVENIENCE,
  ...COMMON_AREAS_SECURITY,
  ...COMMON_AREAS_INFRASTRUCTURE,
].sort((a, b) => a.label.localeCompare(b.label));


export const PRIVATE_AREAS_DETAILS: PropertyFeature[] = [
  { label: "Acabamento de alto padrão", value: "high_standard_finishing" },
  { label: "Aquecedor", value: "heater" },
  { label: "Aquecimento a gás", value: "gas_heating" },
  { label: "Aquecimento central", value: "central_heating" },
  { label: "Armários planejados", value: "custom_cabinets" },
  { label: "Banheira", value: "bathtub" },
  { label: "Banheiro com chuveiro duplo", value: "double_shower" },
  { label: "Blackout nas janelas", value: "blackout_windows" },
  { label: "Box no banheiro", value: "shower_box" },
  { label: "Conceito aberto", value: "open_concept" },
  { label: "Cozinha americana", value: "american_kitchen" },
  { label: "Cozinha planejada", value: "custom_kitchen" },
  { label: "Janelas em alumínio", value: "aluminum_windows" },
  { label: "Lareira", value: "fireplace" },
  { label: "Metais de alto padrão", value: "high_quality_metals" },
  { label: "Móveis planejados", value: "custom_furniture" },
  { label: "Papel de parede", value: "wallpaper" },
  { label: "Pé direito alto", value: "high_ceiling" },
  { label: "Pé direito duplo", value: "double_height_ceiling" },
  { label: "Piso aquecido", value: "heated_floor" },
  { label: "Piso de cerâmica", value: "ceramic_floor" },
  { label: "Piso de granito", value: "granite_floor" },
  { label: "Piso de madeira", value: "wood_floor" },
  { label: "Piso de mármore", value: "marble_floor" },
  { label: "Piso laminado", value: "laminate_floor" },
  { label: "Piso porcelanato", value: "porcelain_floor" },
  { label: "Teto em gesso", value: "plaster_ceiling" },
  { label: "Vista para o mar", value: "ocean_view" },
];

export const PRIVATE_AREAS_ROOMS: PropertyFeature[] = [
  { label: "Adega", value: "wine_cellar" },
  { label: "Ambientes integrados", value: "integrated_environments" },
  { label: "Área de serviço", value: "service_area" },
  { label: "Closet", value: "walk_in_closet" },
  { label: "Cozinha gourmet", value: "gourmet_kitchen" },
  { label: "Cozinha independente", value: "independent_kitchen" },
  { label: "Dependência de empregados", value: "maid_room" },
  { label: "Depósito", value: "storage" },
  { label: "Despensa", value: "pantry" },
  { label: "Dormitório para hóspedes", value: "guest_bedroom" },
  { label: "Entrada de serviço", value: "service_entrance" },
  { label: "Escritório", value: "home_office" },
  { label: "Hall de entrada", value: "entrance_hall" },
  { label: "Lavabo", value: "half_bath" },
  { label: "Lavanderia", value: "laundry" },
  { label: "Mezanino", value: "mezzanine" },
  { label: "Quarto com armário", value: "bedroom_closet" },
  { label: "Quarto com sacada", value: "bedroom_balcony" },
  { label: "Sala conjugada com cozinha", value: "integrated_living_kitchen" },
  { label: "Sala de jantar", value: "dining_room" },
  { label: "Suítes", value: "suites" },
  { label: "Tanque de lavar roupa", value: "laundry_sink" },
];

export const PRIVATE_AREAS_TECH: PropertyFeature[] = [
  { label: "Ar condicionado", value: "air_conditioning" },
  { label: "Elevador privativo", value: "private_elevator" },
  { label: "Fechadura biométrica", value: "biometric_lock" },
  { label: "Infraestrutura de ar condicionado", value: "ac_infrastructure" },
  { label: "Isolamento acústico", value: "soundproofing" },
  { label: "Permite animais", value: "pets_allowed" },
  { label: "Sistema de alarme", value: "alarm_system" },
];

export const PRIVATE_AREAS_OUTDOOR: PropertyFeature[] = [
  { label: "Academia", value: "gym" },
  { label: "Churrasqueira", value: "barbecue_grill" },
  { label: "Deck", value: "deck" },
  { label: "Espaço gourmet", value: "gourmet_space" },
  { label: "Garden", value: "garden" },
  { label: "Hidromassagem", value: "whirlpool" },
  { label: "Jacuzzi", value: "jacuzzi" },
  { label: "Piscina", value: "private_pool" },
  { label: "Sacada", value: "balcony" },
  { label: "Sacada com churrasqueira", value: "balcony_with_barbecue" },
  { label: "Sacada com vista panorâmica", value: "panoramic_view_balcony" },
  { label: "Sauna", value: "sauna" },
  { label: "Varanda", value: "veranda" },
];

export const PRIVATE_AREAS: PropertyFeature[] = [
  ...PRIVATE_AREAS_DETAILS,
  ...PRIVATE_AREAS_ROOMS,
  ...PRIVATE_AREAS_TECH,
  ...PRIVATE_AREAS_OUTDOOR,
].sort((a, b) => a.label.localeCompare(b.label));

export const NEARBY_LOCATIONS: PropertyFeature[] = [
  { label: "Acesso à praia", value: "beach_access" },
  { label: "Frente para o mar", value: "ocean_front" },
  { label: "Próximo ao metrô", value: "near_subway" },
  { label: "Shopping Center", value: "shopping_center" },
  { label: "Farmácia", value: "pharmacy" },
  { label: "Supermercado", value: "supermarket" },
  { label: "Escola", value: "school" },
  { label: "Hospital", value: "hospital" },
  { label: "Parque", value: "park" },
  { label: "Ponto de ônibus", value: "bus_stop" },
  { label: "Restaurantes", value: "restaurants" },
  { label: "Padaria", value: "bakery" },
  { label: "Banco", value: "bank" },
];
