export const RIO_ZONES_FALLBACK: Record<string, string> = {
  // AP-1: Centro
  "Benfica": "Centro",
  "Caju": "Centro",
  "Catumbi": "Centro",
  "Centro": "Centro",
  "Cidade Nova": "Centro",
  "Estácio": "Centro",
  "Gamboa": "Centro",
  "Lapa": "Centro",
  "Mangueira": "Centro",
  "Paquetá": "Centro",
  "Rio Comprido": "Centro",
  "Santa Teresa": "Centro",
  "Santo Cristo": "Centro",
  "Saúde": "Centro",
  "Vasco da Gama": "Centro",
  "São Cristóvão": "Centro",

  // AP-2: Zona Sul (e Grande Tijuca muitas vezes agrupada aqui ou isolada, mas vou seguir o usuario)
  "Botafogo": "Zona Sul",
  "Catete": "Zona Sul",
  "Copacabana": "Zona Sul",
  "Cosme Velho": "Zona Sul",
  "Flamengo": "Zona Sul",
  "Gávea": "Zona Sul",
  "Glória": "Zona Sul",
  "Humaitá": "Zona Sul",
  "Ipanema": "Zona Sul",
  "Jardim Botânico": "Zona Sul",
  "Lagoa": "Zona Sul",
  "Laranjeiras": "Zona Sul",
  "Leblon": "Zona Sul",
  "Leme": "Zona Sul",
  "Rocinha": "Zona Sul",
  "São Conrado": "Zona Sul",
  "Urca": "Zona Sul",
  "Vidigal": "Zona Sul",

  // Grande Tijuca (AP-2 mas socialmente Zona norte as vezes, porem admin AP-2)
  "Alto da Boa Vista": "Zona Norte", // Admin é AP-2, mas popularmente ZN. Vou colocar APs oficiais.
  "Andaraí": "Zona Norte",
  "Grajaú": "Zona Norte",
  "Maracanã": "Zona Norte",
  "Praça da Bandeira": "Zona Norte",
  "Tijuca": "Zona Norte",
  "Vila Isabel": "Zona Norte",

  // AP-3: Zona Norte
  "Abolição": "Zona Norte",
  "Acari": "Zona Norte",
  "Água Santa": "Zona Norte",
  "Anchieta": "Zona Norte",
  "Bancários": "Zona Norte",
  "Barros Filho": "Zona Norte",
  "Bento Ribeiro": "Zona Norte",
  "Bonsucesso": "Zona Norte",
  "Brás de Pina": "Zona Norte",
  "Cachambi": "Zona Norte",
  "Cacuia": "Zona Norte",
  "Campinho": "Zona Norte",
  "Cavalcanti": "Zona Norte",
  "Cidade Universitária": "Zona Norte",
  "Cocotá": "Zona Norte",
  "Coelho Neto": "Zona Norte",
  "Colégio": "Zona Norte",
  "Complexo do Alemão": "Zona Norte",
  "Cordovil": "Zona Norte",
  "Costa Barros": "Zona Norte",
  "Del Castilho": "Zona Norte",
  "Encantado": "Zona Norte",
  "Engenheiro Leal": "Zona Norte",
  "Engenho da Rainha": "Zona Norte",
  "Engenho de Dentro": "Zona Norte",
  "Engenho Novo": "Zona Norte",
  "Freguesia (Ilha)": "Zona Norte",
  "Galeão": "Zona Norte",
  "Guadalupe": "Zona Norte",
  "Higienópolis": "Zona Norte",
  "Honório Gurgel": "Zona Norte",
  "Inhaúma": "Zona Norte",
  "Irajá": "Zona Norte",
  "Jacaré": "Zona Norte",
  "Jacarezinho": "Zona Norte",
  "Jardim América": "Zona Norte",
  "Jardim Carioca": "Zona Norte",
  "Jardim Guanabara": "Zona Norte",
  "Lins de Vasconcelos": "Zona Norte",
  "Madureira": "Zona Norte",
  "Manguinhos": "Zona Norte",
  "Maré": "Zona Norte",
  "Marechal Hermes": "Zona Norte",
  "Maria da Graça": "Zona Norte",
  "Méier": "Zona Norte",
  "Moneró": "Zona Norte",
  "Olaria": "Zona Norte",
  "Osvaldo Cruz": "Zona Norte",
  "Parada de Lucas": "Zona Norte",
  "Parque Anchieta": "Zona Norte",
  "Parque Colúmbia": "Zona Norte",
  "Pavuna": "Zona Norte",
  "Penha": "Zona Norte",
  "Penha Circular": "Zona Norte",
  "Piedade": "Zona Norte",
  "Pilares": "Zona Norte",
  "Pitangueiras": "Zona Norte",
  "Portuguesa": "Zona Norte",
  "Praia da Bandeira": "Zona Norte",
  "Quintino Bocaiúva": "Zona Norte",
  "Ramos": "Zona Norte",
  "Riachuelo": "Zona Norte",
  "Ribeira": "Zona Norte",
  "Rocha": "Zona Norte",
  "Rocha Miranda": "Zona Norte",
  "Sampaio": "Zona Norte",
  "São Francisco Xavier": "Zona Norte",
  "Tauá": "Zona Norte",
  "Tomás Coelho": "Zona Norte",
  "Turiaçu": "Zona Norte",
  "Vaz Lobo": "Zona Norte",
  "Vicente de Carvalho": "Zona Norte",
  "Vila da Penha": "Zona Norte",
  "Vila Kosmos": "Zona Norte",
  "Vista Alegre": "Zona Norte",
  "Zumbi": "Zona Norte",

  // AP-4: Zona Sudoeste (Nova Divisão)
  "Anil": "Zona Sudoeste",
  "Barra da Tijuca": "Zona Sudoeste",
  "Barra Olímpica": "Zona Sudoeste", // New neighborhood mentioned
  "Camorim": "Zona Sudoeste",
  "Cidade de Deus": "Zona Sudoeste",
  "Curicica": "Zona Sudoeste",
  "Freguesia (Jacarepaguá)": "Zona Sudoeste",
  "Gardênia Azul": "Zona Sudoeste",
  "Grumari": "Zona Sudoeste",
  "Itanhangá": "Zona Sudoeste",
  "Jacarepaguá": "Zona Sudoeste",
  "Joá": "Zona Sudoeste",
  "Pechincha": "Zona Sudoeste",
  "Praça Seca": "Zona Sudoeste",
  "Recreio dos Bandeirantes": "Zona Sudoeste",
  "Rio das Pedras": "Zona Sudoeste", // New neighborhood mentioned
  "Tanque": "Zona Sudoeste",
  "Taquara": "Zona Sudoeste",
  "Vargem Grande": "Zona Sudoeste",
  "Vargem Pequena": "Zona Sudoeste",
  "Vila Valqueire": "Zona Sudoeste",

  // AP-5: Zona Oeste
  "Bangu": "Zona Oeste",
  "Barra de Guaratiba": "Zona Oeste",
  "Campo dos Afonsos": "Zona Oeste",
  "Campo Grande": "Zona Oeste",
  "Cosmos": "Zona Oeste",
  "Deodoro": "Zona Oeste",
  "Gericinó": "Zona Oeste",
  "Guaratiba": "Zona Oeste",
  "Ilha de Guaratiba": "Zona Oeste",
  "Inhoaíba": "Zona Oeste",
  "Jardim Sulacap": "Zona Oeste",
  "Magalhães Bastos": "Zona Oeste",
  "Paciência": "Zona Oeste",
  "Padre Miguel": "Zona Oeste",
  "Pedra de Guaratiba": "Zona Oeste",
  "Realengo": "Zona Oeste",
  "Santa Cruz": "Zona Oeste",
  "Santíssimo": "Zona Oeste",
  "Senador Camará": "Zona Oeste",
  "Senador Vasconcelos": "Zona Oeste",
  "Sepetiba": "Zona Oeste",
};
